// scripts/lib/renderSystemMap.js
//
// Renders a system manifest (from server/systemManifest.js) into ONE
// self-contained HTML file — inline CSS, tiny inline JS for tabs/collapse, and
// the manifest inlined as JSON. No CDN, no external assets: it opens anywhere,
// offline. The HTML is fully server-rendered (readable with JS disabled); the
// JS only toggles which tab/section is visible.

function esc(s) {
  if (s == null) return '';
  return String(s)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

const fmt = v => {
  if (v == null) return '—';
  if (typeof v === 'boolean') return v ? 'yes' : 'no';
  if (Array.isArray(v)) return v.length ? v.map(esc).join(', ') : '—';
  return esc(v);
};

const pct = v => (v == null || v === '' ? '—' : `${v}%`);

function chip(label, kind = 'neutral') {
  return `<span class="chip ${kind}">${esc(label)}</span>`;
}

function verdictChip(v) {
  const kind =
    v === 'VALIDATED' ? 'pass' : /^FAILED/.test(v) ? 'fail' : 'muted';
  return chip(v, kind);
}

// key/value rows
function kv(rows) {
  return `<dl class="kv">${rows
    .filter(r => r)
    .map(([k, v]) => `<dt>${esc(k)}</dt><dd>${v}</dd>`)
    .join('')}</dl>`;
}

function table(headers, rows) {
  if (!rows.length) return `<p class="muted">none</p>`;
  return `<table><thead><tr>${headers
    .map(h => `<th>${esc(h)}</th>`)
    .join('')}</tr></thead><tbody>${rows
    .map(r => `<tr>${r.map(c => `<td>${c}</td>`).join('')}</tr>`)
    .join('')}</tbody></table>`;
}

// A promotion progress row: actual vs threshold, colored by whether it clears.
function gateRow(label, actual, threshold, ok, suffix = '') {
  const a = actual == null ? '—' : actual;
  const fillPct =
    actual == null || !threshold
      ? 0
      : Math.max(0, Math.min(100, (actual / threshold) * 100));
  return `<div class="gaterow ${ok ? 'ok' : 'no'}">
    <span class="gl">${esc(label)}</span>
    <span class="gbar"><span class="gfill" style="width:${fillPct}%"></span></span>
    <span class="gv">${esc(a)}${suffix} / ${esc(threshold)}${suffix} ${ok ? '✓' : '✗'}</span>
  </div>`;
}

// -------------------------------------------------------------------------

function renderOverview(m) {
  const byTier = {};
  for (const b of m.brokers)
    if (!b.invalid) byTier[b.tier] = (byTier[b.tier] || 0) + 1;
  const tierChips = Object.entries(byTier)
    .map(([t, n]) => chip(`${n} ${t}`, t === 'paper' ? 'gold' : 'muted'))
    .join(' ');
  const verdictChips = Object.entries(m.evals.verdictTally)
    .map(([v, n]) => `${verdictChip(v)}<span class="tally">×${n}</span>`)
    .join(' ');

  const sent = m.signals.semiconductor.live;
  const sentLine = sent.available
    ? `${chip(sent.direction, sent.direction === 'bullish' ? 'pass' : sent.direction === 'bearish' ? 'fail' : 'muted')} conf ${sent.confidence}% → ${esc(sent.recommendedSymbol || '—')} ${sent.canTrade ? '✓ can-trade' : '· hold'}`
    : `<span class="muted">${esc(sent.reason)}</span>`;

  const macro = m.gates.macro.live;

  return `
  <section class="tabpanel" id="tab-overview">
    <div class="grid">
      <div class="card">
        <h3>Snapshot</h3>
        ${kv([
          ['generated', esc(m.meta.generatedAt)],
          ['git', m.meta.gitSha ? chip(m.meta.gitSha, 'muted') : '—'],
          [
            'mode',
            m.meta.live
              ? chip('live readings', 'pass')
              : chip('offline / config-only', 'muted'),
          ],
          ['brokers', m.meta.brokerCount],
        ])}
      </div>
      <div class="card">
        <h3>Broker tiers</h3>
        <p>${tierChips || '—'}</p>
        <h3 style="margin-top:14px">Semiconductor sentiment</h3>
        <p>${sentLine}</p>
        <h3 style="margin-top:14px">Macro gate</h3>
        <p>${macro.state === 'available' ? chip('live', 'pass') + ' ' + esc(macro.reason || '') : chip(macro.state, 'muted') + ' ' + esc(macro.reason || '')}</p>
      </div>
      <div class="card">
        <h3>Backtest verdicts <span class="muted">(${m.evals.totalRuns} runs)</span></h3>
        <p class="chiprow">${verdictChips || '—'}</p>
        <p class="muted small">A strategy is VALIDATED only by clearing all five gates. Most fail — that's the point.</p>
      </div>
    </div>
    <div class="callout warn">
      <strong>Config drift watch.</strong> ${esc(m.exits.driftWarning)}
    </div>
    <p class="muted small">This page is generated by <code>npm run system-map</code>. Every value is read from source (exported constants, .md frontmatter, session state, run artifacts) — re-run to refresh.</p>
  </section>`;
}

function renderBrokers(m) {
  const cards = m.brokers
    .map(b => {
      if (b.invalid) {
        return `<div class="card broker invalid"><h3>${esc(b.file)} ${chip('INVALID', 'fail')}</h3><p class="muted small">${(b.errors || []).map(esc).join('<br>')}</p></div>`;
      }
      const risk = b.risk || {};
      const regime = b.regime || {};
      const macro = b.macro || {};
      const plugins = Object.entries(b.plugins || {})
        .filter(([, v]) => v && Object.keys(v).length)
        .map(([k, v]) => `<code>${esc(k)}</code>: ${esc(JSON.stringify(v))}`)
        .join('<br>');

      // Live block
      let liveBlock = `<p class="muted small">not materialized as a session</p>`;
      if (b.live) {
        const s = b.live.stats;
        liveBlock = kv([
          [
            'status',
            chip(b.live.status, b.live.status === 'running' ? 'pass' : 'muted'),
          ],
          ['trades', `${s.totalTrades} (${s.wins}W / ${s.losses}L)`],
          // stats.winRate is stored as a percent already (e.g. 22.2), not a fraction.
          ['win rate', pct(s.winRate == null ? null : Math.round(s.winRate))],
          ['total P&L', s.totalPnL == null ? '—' : `$${s.totalPnL}`],
          ['max DD', pct(s.maxDrawdown)],
          ['cons. losses', s.consecutiveLosses],
          [
            'sharpe',
            s.sharpe == null
              ? '<span class="muted">n/a (&lt;2 days)</span>'
              : s.sharpe,
          ],
          b.live.positions.length
            ? [
                'positions',
                b.live.positions
                  .map(p => `${esc(p.symbol)}×${esc(p.qty)}`)
                  .join(', '),
              ]
            : null,
        ]);
      }

      // Promotion block — real evaluator output + progress vs PROMOTE thresholds
      let promoBlock = '';
      if (b.promotion) {
        const P = m.promotion.PROMOTE;
        const mt = b.promotion.metrics || {};
        const actionKind =
          b.promotion.action === 'promote'
            ? 'pass'
            : b.promotion.action === 'fire' ||
                b.promotion.action === 'demote' ||
                b.promotion.action === 'defund'
              ? 'fail'
              : 'muted';
        const bars =
          b.tier === 'simulated'
            ? `
          ${gateRow('Sharpe', mt.sharpe, P.minSharpe, mt.sharpe != null && mt.sharpe >= P.minSharpe)}
          ${gateRow('Win rate', mt.winRate == null ? null : Math.round(mt.winRate * 100), Math.round(P.minWinRate * 100), mt.winRate * 100 >= P.minWinRate * 100, '%')}
          ${gateRow('Max DD', mt.maxDD, P.maxDrawdownPct, mt.maxDD <= P.maxDrawdownPct, '%')}
          ${gateRow('Trades', mt.totalTrades, P.minTrades, mt.totalTrades >= P.minTrades)}
          ${gateRow('Days', mt.days, P.minDays, mt.days >= P.minDays)}`
            : `<p class="muted small">paper-tier — evaluated against DEMOTE/FIRE, not promotion bars.</p>`;
        promoBlock = `
        <div class="promo">
          <p>${chip(b.promotion.action, actionKind)} <span class="muted small">${esc(b.promotion.reason)}</span></p>
          ${bars}
          ${b.promotion.edge ? `<p class="small">Edge gate: ${b.promotion.edge.pass ? chip('pass', 'pass') : chip('fail', 'fail')} <span class="muted">${esc(b.promotion.edge.reason)}</span></p>` : ''}
        </div>`;
      }

      const et = b.exitTunables || {};

      return `<div class="card broker">
        <div class="broker-head">
          <h3>${esc(b.name)} <span class="muted small">${esc(b.slug)}</span></h3>
          <div>${chip(b.tier, b.tier === 'paper' ? 'gold' : 'muted')} ${chip(b.strategy, 'neutral')}</div>
        </div>
        <div class="broker-grid">
          <div>
            <h4>Config</h4>
            ${kv([
              ['capital', `$${esc(b.capital)}`],
              ['effective', `$${esc(b.effectiveCapital)}`],
              ['watchlist', fmt(b.watchlist)],
              [
                'risk/trade',
                pct(
                  risk.perTrade == null
                    ? null
                    : (risk.perTrade * 100).toFixed(2)
                ),
              ],
              [
                'max drawdown',
                pct(
                  risk.maxDrawdown == null
                    ? null
                    : (risk.maxDrawdown * 100).toFixed(0)
                ),
              ],
              ['sizing', fmt(risk.sizing)],
              ['kelly frac', fmt(risk.kellyFraction)],
              ['max positions', fmt(risk.maxPositions)],
              ['max pos size', pct(risk.maxPositionSizePercent)],
              [
                'daily-loss rail',
                risk.dailyLossLimit == null
                  ? '<span class="muted">off</span>'
                  : pct((risk.dailyLossLimit * 100).toFixed(1)),
              ],
              [
                'cons-loss rail',
                risk.maxConsecutiveLosses == null
                  ? '<span class="muted">off</span>'
                  : risk.maxConsecutiveLosses,
              ],
              [
                'regime gate',
                regime.enabled
                  ? `${chip('on', 'pass')} ${esc(regime.preferred)} [${(regime.entropyWindows || []).join(',')}]`
                  : chip('off', 'muted'),
              ],
              [
                'macro gate',
                macro.enabled
                  ? `${chip('on', 'pass')} ×${esc(macro.riskOffScalar)}`
                  : chip('off', 'muted'),
              ],
              plugins ? ['plugins', plugins] : null,
            ])}
            <h4 style="margin-top:12px">Exit tunables</h4>
            ${kv([
              ['stop loss', pct(et.stopLossPercent)],
              ['take profit', pct(et.takeProfitPercent)],
              [
                'trailing',
                et.trailingStopPercent
                  ? pct(et.trailingStopPercent)
                  : '<span class="muted">off</span>',
              ],
              ['RSI overbought', fmt(et.rsiOverbought)],
              [
                'EOD exit',
                et.exitBeforeClose === false
                  ? '<span class="muted">off</span>'
                  : `${et.exitBeforeCloseMinutes}min`,
              ],
              ['min profit exit', fmt(et.minProfitForExitPercent)],
              ['dampening', fmt(et.trendDampeningFactor)],
            ])}
          </div>
          <div>
            <h4>Live</h4>
            ${liveBlock}
            <h4 style="margin-top:12px">Promotion status</h4>
            ${promoBlock || '<p class="muted small">—</p>'}
          </div>
        </div>
        <details><summary>persona</summary><pre class="persona">${esc(b.personaExcerpt)}</pre></details>
      </div>`;
    })
    .join('');
  return `<section class="tabpanel hidden" id="tab-brokers">${cards}</section>`;
}

function renderGates(m) {
  const g = m.gates;
  const railRows = g.rails.brokers.map(r => [
    esc(r.slug),
    r.dailyLossLimit == null
      ? '<span class="muted">off</span>'
      : pct((r.dailyLossLimit * 100).toFixed(1)),
    r.maxConsecutiveLosses == null
      ? '<span class="muted">off</span>'
      : esc(r.maxConsecutiveLosses),
    r.currentConsecutiveLosses == null ? '—' : esc(r.currentConsecutiveLosses),
    r.maxPortfolioDrawdown == null
      ? '<span class="muted">off</span>'
      : pct((r.maxPortfolioDrawdown * 100).toFixed(0)),
  ]);
  return `<section class="tabpanel hidden" id="tab-gates">
    <div class="grid">
      <div class="card">
        <h3>Entropy gate ${chip('OFF', 'fail')}</h3>
        <p class="muted small">${esc(g.entropy.status)}</p>
        <p class="small">${esc(g.entropy.note)}</p>
        ${kv([
          [
            'default windows',
            (g.entropy.defaults.entropyWindows || []).join(', '),
          ],
          ['preferred', esc(g.entropy.defaults.preferred)],
          ['block on transition', fmt(g.entropy.defaults.blockOnTransition)],
          ['enabled brokers', fmt(g.entropy.enabledBrokers)],
        ])}
      </div>
      <div class="card">
        <h3>Macro regime gate</h3>
        <p class="small">${esc(g.macro.note)}</p>
        ${kv([
          ['risk-off scalar', `×${esc(g.macro.riskOffScalarDefault)}`],
          ['deep inversion', esc(g.macro.DEEP_INVERSION)],
          ['HY spike mult', `×${esc(g.macro.HY_SPIKE_MULT)}`],
          [
            'series',
            `${esc(g.macro.series.curveSlope)} · ${esc(g.macro.series.hySpread)}`,
          ],
          [
            'live',
            g.macro.live.state === 'available'
              ? chip('available', 'pass')
              : chip(g.macro.live.state, 'muted') +
                ' ' +
                esc(g.macro.live.reason || ''),
          ],
          ['enabled brokers', fmt(g.macro.enabledBrokers)],
        ])}
      </div>
      <div class="card">
        <h3>Kelly sizing</h3>
        <p class="small">${esc(g.kelly.note)}</p>
        ${kv([
          ['min trades (empirical)', g.kelly.MIN_TRADES_FOR_EMPIRICAL],
          ['min losses (payoff)', g.kelly.MIN_LOSSES_FOR_PAYOFF],
          ['max win rate', g.kelly.MAX_WIN_RATE],
          ['prior win rate', g.kelly.PRIOR_WIN_RATE],
          ['prior payoff', g.kelly.PRIOR_PAYOFF_RATIO],
          ['rolling window', g.kelly.ROLLING_WINDOW],
          [
            'fallbacks',
            `mult ${g.kelly.fallbacks.fractionMult}, max ${g.kelly.fallbacks.maxPercent}%, min ${g.kelly.fallbacks.minPercent}%`,
          ],
        ])}
      </div>
    </div>
    <div class="card">
      <h3>Risk rails <span class="muted small">(per-broker opt-in)</span></h3>
      <p class="small">${esc(g.rails.note)}</p>
      ${table(['broker', 'daily-loss', 'cons-loss limit', 'cons-loss now', 'portfolio DD'], railRows)}
    </div>
  </section>`;
}

function renderSignals(m) {
  const s = m.signals;
  const cfg = s.semiconductor.config;
  const live = s.semiconductor.live;
  const weightRows = s.semiconductor.model.signals.map(w => [
    esc(w.key),
    `+${esc(w.points)}`,
    esc(w.weightLabel),
    `<span class="muted small">${esc(w.note)}</span>`,
  ]);
  const strategyRows = s.strategies.allowed.map(st => [
    `<code>${esc(st)}</code>`,
    (s.strategies.inUse[st] || []).length
      ? s.strategies.inUse[st].map(esc).join(', ')
      : '<span class="muted">—</span>',
  ]);
  const techRows = s.technicals.indicators.map(t => [
    `<code>${esc(t.key)}</code>`,
    `<span class="muted small">${esc(t.use)}</span>`,
  ]);

  return `<section class="tabpanel hidden" id="tab-signals">
    <div class="card">
      <h3>Semiconductor sentiment <span class="muted small">SOXX → SOXL/SOXS</span></h3>
      <p class="small">${esc(s.semiconductor.note)}</p>
      <div class="grid2">
        <div>
          <h4>Live reading</h4>
          ${
            live.available
              ? kv([
                  [
                    'direction',
                    chip(
                      live.direction,
                      live.direction === 'bullish'
                        ? 'pass'
                        : live.direction === 'bearish'
                          ? 'fail'
                          : 'muted'
                    ),
                  ],
                  ['confidence', pct(live.confidence)],
                  ['recommends', fmt(live.recommendedSymbol)],
                  ['can trade', fmt(live.canTrade)],
                  ['stale', fmt(live.stale)],
                  live.signals && live.signals.length
                    ? ['signals', live.signals.map(esc).join('<br>')]
                    : null,
                ])
              : `<p class="muted small">${esc(live.reason)}</p>`
          }
        </div>
        <div>
          <h4>Thresholds <span class="muted small">(live config)</span></h4>
          ${kv([
            ['min conf to trade', pct(cfg.minConfidenceToTrade)],
            ['high confidence', pct(cfg.highConfidence)],
            ['switch confidence', pct(cfg.switchConfidence)],
            ['base entry', pct(cfg.baseEntryThreshold)],
            ['base exit', pct(cfg.baseExitThreshold)],
            ['vol multiplier', `×${esc(cfg.volatilityMultiplier)}`],
            ['clamp', `${cfg.minThreshold}%–${cfg.maxThreshold}%`],
            ['cache TTL', `${(s.semiconductor.cacheTTLms || 0) / 1000}s`],
          ])}
        </div>
      </div>
      <h4 style="margin-top:12px">Confidence weights <span class="muted small">(base ${s.semiconductor.model.baseConfidence}, eff. threshold ×${s.semiconductor.model.effectiveThresholdMult})</span></h4>
      ${table(['signal', 'points', 'weight', 'note'], weightRows)}
    </div>
    <div class="grid2">
      <div class="card">
        <h3>Strategies</h3>
        ${table(['strategy', 'brokers using'], strategyRows)}
      </div>
      <div class="card">
        <h3>Technical indicators</h3>
        <p class="small">${esc(s.technicals.note)}</p>
        ${table(['indicator', 'use'], techRows)}
      </div>
    </div>
  </section>`;
}

function renderExits(m) {
  const e = m.exits;
  const weightRows = e.model.weights.map(w => [
    esc(w.key),
    `${w.points >= 0 ? '+' : ''}${esc(w.points)}`,
    w.critical ? chip('critical', 'gold') : chip('dampenable', 'muted'),
    `<span class="muted small">${esc(w.note)}</span>`,
  ]);
  const tuneRows = e.perBrokerTunables.map(t => [
    esc(t.slug),
    pct(t.stopLossPercent),
    pct(t.takeProfitPercent),
    t.trailingStopPercent
      ? pct(t.trailingStopPercent)
      : '<span class="muted">off</span>',
    fmt(t.rsiOverbought),
    t.exitBeforeClose === false
      ? '<span class="muted">off</span>'
      : `${t.exitBeforeCloseMinutes}m`,
    fmt(t.trendDampeningFactor),
  ]);
  return `<section class="tabpanel hidden" id="tab-exits">
    <div class="callout warn"><strong>Drift:</strong> ${esc(e.driftWarning)}</div>
    <div class="card">
      <h3>Exit score model</h3>
      <p class="small">${esc(e.note)}</p>
      ${kv([
        ['trigger (base)', `≥ ${e.model.trigger.base}`],
        ['trigger (tiny profit)', `≥ ${e.model.trigger.tinyProfit}`],
        ['dampening', `<code>${esc(e.model.dampening.formula)}</code>`],
        ['dampening applies', esc(e.model.dampening.appliesWhen)],
      ])}
      <h4 style="margin-top:12px">Weights</h4>
      ${table(['signal', 'points', 'class', 'note'], weightRows)}
    </div>
    <div class="card">
      <h3>Per-broker exit tunables</h3>
      ${table(['broker', 'stop', 'TP', 'trailing', 'RSI OB', 'EOD', 'dampen'], tuneRows)}
    </div>
  </section>`;
}

function renderEvals(m) {
  const e = m.evals;
  const gateRows = e.fiveGates.map((g, i) => [
    `${i + 1}. <code>${esc(g.key)}</code>`,
    `<span class="muted small">${esc(g.checks)}</span>`,
  ]);
  const runRows = e.recentRuns.map(r => [
    `<span class="small">${esc(r.family)}/${esc(r.strategyId)}</span>`,
    verdictChip(r.verdict),
    r.sharpe == null ? '—' : esc(r.sharpe),
    r.maxDD == null ? '—' : esc(r.maxDD),
    `<span class="muted small">${esc((r.generatedAt || '').slice(0, 10))}</span>`,
  ]);
  const certRows = e.certifications.map(c => [
    `<code>${esc(c.name)}</code>`,
    esc((c.generatedAt || '').slice(0, 10) || '—'),
    c.ageDays == null
      ? '—'
      : `${esc(c.ageDays)}d ${c.ageDays > 30 ? chip('stale', 'fail') : chip('fresh', 'pass')}`,
  ]);
  const vs = e.validatedSources;
  const vsKeys = Object.keys(vs.registry || {});
  return `<section class="tabpanel hidden" id="tab-evals">
    <div class="card">
      <h3>The five validation gates</h3>
      <p class="muted small">A strategy is VALIDATED only by clearing all five, in order.</p>
      ${table(['gate', 'checks'], gateRows)}
    </div>
    <div class="grid2">
      <div class="card">
        <h3>Verdict tally <span class="muted small">(${e.totalRuns} runs)</span></h3>
        <p class="chiprow">${Object.entries(e.verdictTally)
          .map(([v, n]) => `${verdictChip(v)}<span class="tally">×${n}</span>`)
          .join(' ')}</p>
      </div>
      <div class="card">
        <h3>Event-source validation</h3>
        ${kv([
          ['requires validation', fmt(vs.requiresEventValidation)],
          ['max age', `${vs.maxAgeDays} days`],
          ['dark-pool archive min', `${vs.eventStudyMinArchiveDays} days`],
          [
            'validated registry',
            vsKeys.length
              ? fmt(vsKeys)
              : '<span class="muted">empty — none validated yet</span>',
          ],
        ])}
      </div>
    </div>
    <div class="card">
      <h3>Faithfulness certifications</h3>
      ${table(['cert', 'generated', 'age'], certRows)}
    </div>
    <div class="card">
      <h3>Recent runs <span class="muted small">(latest 25)</span></h3>
      ${table(['strategy', 'verdict', 'sharpe', 'maxDD', 'date'], runRows)}
    </div>
  </section>`;
}

function renderPromotion(m) {
  const p = m.promotion;
  const asTable = obj =>
    table(
      ['param', 'value'],
      Object.entries(obj).map(([k, v]) => [`<code>${esc(k)}</code>`, esc(v)])
    );
  return `<section class="tabpanel hidden" id="tab-promotion">
    <p class="small">${esc(p.note)}</p>
    <div class="grid">
      <div class="card"><h3>Promote (sim → paper)</h3>${asTable(p.PROMOTE)}</div>
      <div class="card"><h3>Edge gate</h3>${asTable(p.EDGE_GATE)}</div>
      <div class="card"><h3>Demote (paper → sim)</h3>${asTable(p.DEMOTE)}</div>
      <div class="card"><h3>Fire</h3>${asTable(p.FIRE)}</div>
      <div class="card"><h3>Auto-defund (proven loser)</h3>${asTable(p.DEFUND)}</div>
      <div class="card"><h3>Tiers &amp; breeding</h3>
        <p>${(p.tiers || []).map(t => chip(t, 'muted')).join(' ')}</p>
        <p class="small" style="margin-top:8px">${esc(p.breeding)}</p>
      </div>
    </div>
  </section>`;
}

const TABS = [
  ['overview', 'Overview'],
  ['brokers', 'Brokers'],
  ['gates', 'Gates'],
  ['signals', 'Signals'],
  ['exits', 'Exits'],
  ['evals', 'Evals'],
  ['promotion', 'Promotion'],
  ['raw', 'Raw JSON'],
];

function renderHtml(m) {
  const nav = TABS.map(
    ([id, label], i) =>
      `<button class="tabbtn ${i === 0 ? 'active' : ''}" data-tab="${id}" onclick="showTab('${id}')">${esc(label)}</button>`
  ).join('');

  const rawJson = esc(JSON.stringify(m, null, 2));

  return `<!doctype html>
<html lang="en"><head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>System Map — ${esc(m.meta.generatedAt)}</title>
<style>
  :root {
    --bg:#17140f; --panel:#211d16; --panel2:#2a251c; --line:#3a3325;
    --ink:#e9ddc4; --muted:#9b9078; --gold:#c9a24b; --green:#7bb37b; --red:#cf7b6f; --orange:#d9a05b;
  }
  * { box-sizing:border-box; }
  body { margin:0; background:var(--bg); color:var(--ink);
    font-family:ui-monospace,"SF Mono",Menlo,Consolas,monospace; font-size:13px; line-height:1.5; }
  header { padding:18px 22px; border-bottom:1px solid var(--line); background:linear-gradient(180deg,#211d16,#17140f); }
  header h1 { margin:0; font-size:19px; letter-spacing:.5px; color:var(--gold); }
  header .sub { color:var(--muted); font-size:12px; margin-top:4px; }
  nav { position:sticky; top:0; z-index:5; display:flex; flex-wrap:wrap; gap:2px; padding:8px 18px;
    background:var(--bg); border-bottom:1px solid var(--line); }
  .tabbtn { background:transparent; color:var(--muted); border:1px solid transparent; border-radius:6px;
    padding:6px 12px; font:inherit; cursor:pointer; }
  .tabbtn:hover { color:var(--ink); }
  .tabbtn.active { color:var(--bg); background:var(--gold); border-color:var(--gold); font-weight:600; }
  main { padding:18px 22px; max-width:1200px; margin:0 auto; }
  .tabpanel.hidden { display:none; }
  .grid { display:grid; grid-template-columns:repeat(auto-fit,minmax(280px,1fr)); gap:14px; }
  .grid2 { display:grid; grid-template-columns:1fr 1fr; gap:14px; }
  @media(max-width:720px){ .grid2{grid-template-columns:1fr;} }
  .card { background:var(--panel); border:1px solid var(--line); border-radius:10px; padding:14px 16px; margin-bottom:14px; }
  .card h3 { margin:0 0 10px; font-size:14px; color:var(--gold); }
  .card h4 { margin:0 0 6px; font-size:12px; color:var(--muted); text-transform:uppercase; letter-spacing:.5px; }
  .broker-head { display:flex; justify-content:space-between; align-items:flex-start; gap:10px; flex-wrap:wrap; }
  .broker-grid { display:grid; grid-template-columns:1fr 1fr; gap:18px; margin-top:8px; }
  .broker-grid > div { min-width:0; }
  @media(max-width:720px){ .broker-grid{grid-template-columns:1fr;} }
  dl.kv { display:grid; grid-template-columns:auto 1fr; gap:3px 12px; margin:0; }
  dl.kv dt { color:var(--muted); }
  dl.kv dd { margin:0; text-align:right; min-width:0; overflow-wrap:anywhere; word-break:break-word; }
  table { width:100%; border-collapse:collapse; font-size:12px; }
  th,td { text-align:left; padding:5px 8px; border-bottom:1px solid var(--line); vertical-align:top; }
  th { color:var(--muted); font-weight:600; }
  td:not(:first-child), th:not(:first-child) { text-align:right; }
  .chip { display:inline-block; padding:1px 8px; border-radius:20px; font-size:11px; border:1px solid var(--line); }
  .chip.pass { color:var(--green); border-color:var(--green); }
  .chip.fail { color:var(--red); border-color:var(--red); }
  .chip.gold { color:var(--gold); border-color:var(--gold); }
  .chip.muted { color:var(--muted); }
  .chip.neutral { color:var(--ink); }
  .chiprow .tally { color:var(--muted); margin:0 8px 0 2px; font-size:11px; }
  .callout { border-radius:10px; padding:10px 14px; margin:0 0 14px; border:1px solid var(--orange); background:rgba(217,160,91,.08); }
  .callout.warn strong { color:var(--orange); }
  .muted { color:var(--muted); }
  .small { font-size:11.5px; }
  code { background:var(--panel2); padding:1px 5px; border-radius:4px; color:var(--gold); font-size:12px; }
  pre { background:var(--panel2); border:1px solid var(--line); border-radius:8px; padding:12px; overflow:auto; font-size:11.5px; }
  pre.persona { max-height:220px; }
  details summary { cursor:pointer; color:var(--muted); margin-top:8px; }
  .gaterow { display:grid; grid-template-columns:78px 1fr auto; align-items:center; gap:8px; margin:3px 0; font-size:11.5px; }
  .gaterow .gl { color:var(--muted); }
  .gaterow .gbar { height:6px; background:var(--panel2); border-radius:4px; overflow:hidden; }
  .gaterow .gfill { display:block; height:100%; background:var(--muted); }
  .gaterow.ok .gfill { background:var(--green); }
  .gaterow.no .gfill { background:var(--red); }
  .promo { border-top:1px solid var(--line); padding-top:8px; }
  .broker.invalid { border-color:var(--red); }
  footer { color:var(--muted); text-align:center; padding:20px; font-size:11px; }
</style>
</head><body>
<header>
  <h1>⬖ System Map</h1>
  <div class="sub">Generated ${esc(m.meta.generatedAt)} · git ${esc(m.meta.gitSha || 'n/a')} · ${m.meta.live ? 'live readings' : 'offline / config-only'} · ${m.meta.brokerCount} brokers</div>
</header>
<nav>${nav}</nav>
<main>
  ${renderOverview(m)}
  ${renderBrokers(m)}
  ${renderGates(m)}
  ${renderSignals(m)}
  ${renderExits(m)}
  ${renderEvals(m)}
  ${renderPromotion(m)}
  <section class="tabpanel hidden" id="tab-raw">
    <div class="card"><h3>Full manifest (source of every value on this page)</h3><pre>${rawJson}</pre></div>
  </section>
</main>
<footer>Reflect, don't transcribe — every value read from source at generation time. Re-run <code>npm run system-map</code> to refresh.</footer>
<script>
  function showTab(id){
    document.querySelectorAll('.tabpanel').forEach(function(p){ p.classList.toggle('hidden', p.id !== 'tab-'+id); });
    document.querySelectorAll('.tabbtn').forEach(function(b){ b.classList.toggle('active', b.dataset.tab === id); });
    if (history.replaceState) history.replaceState(null,'','#'+id);
  }
  var h = (location.hash || '').replace('#','');
  if (h) showTab(h);
</script>
</body></html>`;
}

module.exports = { renderHtml };
